### ISSUE TITLE
Компонент MenuTop

### ISSUE THREAD

**Issue by acces5denied-dev** [Bertik888/Samokat_proj_Vue3_vuex_router#4]
Сделать компонент MenuTop у которого будет 

`props: {
  items: {
    type: Array,
    default: () => []
  }
}`

items - массив элементов меню, структура которого:
```
[{
  title: 'test 1',
  route: ''
},
{
  title: 'test 2',
  route: ''
},
.....
{
  title: 'test 3',
  route: ''
}]
```
[ссылка на макет](https://www.figma.com/file/X99yH1Igkd3gcMP4hFaFCQ/Untitled?type=design&node-id=0-6&mode=design&t=fkk2nOwsCcsfeJ5e-0)

```
<!-- используем компонент router-link для навигации -->
<!-- входной параметр `to` определяет URL для перехода -->
<!-- `<router-link>` по умолчанию отображается тегом `<a>` -->
<router-link to="/foo" class="test">Перейти к Foo</router-link>
// код выше аналогичен коду ниже
<a href="/foo" class="test">Перейти к Foo</a>
```
навигацию делаем семантически правильно используя корневой тег  nav

```
//MenuTop
<nav class="menu-top">
  <router-link
    v-for="(item, idx) in items"
    :key="idx"
    :to="item.route"
    class="menu-top__item"
  >
    {{ item.title }}
  </router-link>
</nav>
```

Обратите внимание, что `<router-link>` автоматически получает класс .router-link-active при совпадении маршрута.  Поэтому нужно будет описать этот класс в стилях для данного компонента (сделать его синим как в макете)

```
<style lang="scss">
.menu-top {
// какие то свойства
  &__items {
  // какие то свойства
    &.router-link-active {
        color: синий;
    }
  }
}
</style>
```

```
//APP template
<menu-top :items="menuTopList" />

//APP script
data() {
  return {
    menuTopList: [
      {
        title: 'test 1',
        route: ''
      },
      {
        title: 'test 2',
        route: ''
      },
      {
        title: 'test 3',
        route: ''
      },
      {
        title: 'test 4',
        route: ''
      }
    ]
  }
}
```

Доп. материалы:
[подробнее про vueRouter](https://v3.router.vuejs.org/ru/guide/#html)
[подробнее про семантику](https://msiter.ru/tutorials/html5/semantic_elements)

**Comment by Bertik888** [comment]
Меню подготовлено
